CREATE TABLE raw_fannie_origination (
	loan_identifier text,
	origination_channel text,
	seller_name text,
	original_interest_rate numeric,
	original_upb numeric,
	original_loan_term numeric,
	origination_date numeric,
	first_payment_date numeric,
	original_loan_to_value numeric,
	original_combined_loan_to_value numeric,
	number_of_borrowers	numeric,
	original_debt_to_income_ratio numeric,
	borrower_credit_score_at_origination numeric,
	first_time_homebuyer_indicator text,
	loan_purpose text,
	property_type text,
	number_of_units text,
	occupancy_type text,
	property_state text,
	zip_code_short text,
	primary_mortgage_insurance_percent numeric,
	product_type text,
	coborrower_credit_score_at_origination numeric,
	mortgage_insurance_type numeric,
	relocation_mortgage_indicator text
);
