CREATE TABLE raw_freddie_performance (
	loan_sequence_number text,
	monthly_reporting_period numeric,
	current_actual_upb numeric,
	current_loan_delinquency_status text,
	loan_age numeric,
	remaining_months_to_legal_maturity numeric,
	repurchase_flag text,
	modification_flag text,
	zero_balance_code numeric,
	zero_balance_effective_date numeric,
	current_interest_rate numeric,
	current_deferred_upb numeric,
	due_date_of_last_paid_installment numeric,
	mortgage_insurance_recoveries numeric,
	net_sales_proceeds text,
	non_mortgage_insurance_recoveries numeric,
	expenses numeric,
	legal_costs numeric,
	maintenance_and_preservation_costs numeric,
	taxes_and_insurance numeric,
	miscellaneous_expenses numeric,
	actual_loss_calculation numeric,
	modification_cost numeric,
	step_modification_flag text,
	deferred_payment_modification text,
	estimated_loan_to_value numeric
);
